---
- hosts: all
  become: yes
  tasks:
  - name: deploy application into tomcat
    get_url:
      url: http://3.15.24.139:8081/nexus/service/local/repositories/Sathish/content/Nexus/sparkjava/1.0/sparkjava-1.0.war
      dest: /opt/tomcat/webapps
